version: '3.4'

services:
  contactdb:
    image: mongo
  setur.services.contact.api:
    image: ${DOCKER_REGISTRY-}seturservicescontactapi
    build:
      context: .
      dockerfile: Setur.Services.Contact/src/Setur.Services.Contact.Api/Dockerfile
  setur.services.report.api:
    image: ${DOCKER_REGISTRY-}seturservicesreportapi
    build:
      context: .
      dockerfile: Setur.Services.Report/src/Setur.Services.Report.Api/Dockerfile
  rabbitmq:
    image: rabbitmq:3-management
