version: '3.4'

services:
  contactdb:
    container_name: contactdb
    restart: always
    volumes:
        - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
        - "27018:27017"
    environment:
        - TZ=Europe/Istanbul
  setur.services.contact.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings:ConnectionString=mongodb://db:27017
    ports:
      - "5050:80"
  setur.services.report.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings:ConnectionString=mongodb://db:27017
    ports:
      - "5051:8080"
  rabbitmq:
    container_name: rabbitmq
    restart: unless-stopped
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq:/var/lib/rabbitmq

volumes:
   rabbitmq:
     driver: local
